[Root]
name=root
path=C:\Users\wz\Desktop\tools\developer

; 在此处添加你的软件配置
; 示例：
; [SoftwareName]
; name=软件显示名称
; path=C:\Path\To\Software.exe

[folder-explorer]
name=folder-explorer
path=C:\Users\wz\Desktop\tools\developer\folder-explorer.lnk


[Docker Desktop]
name=Docker Desktop
path=C:\Program Files\Docker\Docker\Docker Desktop.exe

[IntelliJ IDEA]
name=IntelliJ IDEA
path=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\JetBrains\IntelliJ IDEA 2021.3.3.lnk

[vscode]
name=vscode
path=C:\Users\wz\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code\Visual Studio Code.lnk

[postman]
name=postman
path=C:\Users\wz\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Postman\Postman.lnk

[Apifox]
name=Apifox
path=C:\Users\wz\AppData\Local\Programs\Apifox\Apifox.exe

[navicat]
name=navicat
path=C:\Users\wz\Desktop\tools\developer\Navicat\Navicat Premium 15\navicat.exe
